#palavras usadas no jogo da forca


#Lista com as frutas
frutas = [
    'c a c a u',
    'c a r a m b o l a',
    'f r a m b o e s a',
    'k i w i',
    'l a r a n j a',
    'm a c a',
    'b a n a n a',
    'a b a c a x i',
    'j a c a',
    'c o c o',
    'g o i a b a',
    'j a b u t i c a b a',
    'm a m a o',
    'm a n g a b a',
    'a m o r a',
    'a c e r o l a',
    'c a s t a n h a',
    'l i m a o',
    'p e r a',
    'u v a',
    'j a m b o',
    'c a q u i',
    'c i d r a',
    'f i g o',
    'g r o s e l h a',
    'm e l a o',
    'p e q u i',
    'p i t o m b a',
    'n o z',
    'c a j u',
    'c a m b u c i',
    's a p o t i',
    'a m e i x a',
]

#Lista com os animais
animais = [
    'c a c h o r r o', 
    'g a t o',
    'p e i x e',
    'z e b r a',
    'c a m a l e a o',
    'l e a o',
    'l o b o',
    'a v e s t r u z',
    'c a v a l o',
    'c a m e l o',
    't u b a r a o',
    'b o i',
    't i g r e',
    'm a c a c o',
    'c o b r a',
    'l a g a r t o',
    'c a b r a',
    'v a c a',
    'g a n s o',
    'c o r v o',
    'r a t o'

]

paises = [
    'b r a s i l',
    'v e n e z u e l a',
    'p a r a g u a i',
    'u r u g u a i',
    'c h i l e',
    'a r g e n t i n a',
    'p e r u',
    'h a i t i',
    'p o r t u g a l',
    'j a p a o',
    'c h i n a',
    'a l e m a n h a',
    'r u s s i a',
    'p o l o n i a',
    'm e x i c o',
    'c a n a d a',
    'f r a n c a',
    'b o l i v i a',
    'c o l o m b i a',
    'u c r a n i a',
    'c a n a d a',
    'n o r u e g a',
]